// <auto-generated />
using BizHacks.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BizHacks.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizHacks.Models.Display", b =>
                {
                    b.Property<int>("DisplayId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BounceRate");

                    b.Property<string>("CTR");

                    b.Property<string>("CampaignName");

                    b.Property<string>("Clicks");

                    b.Property<string>("Cost");

                    b.Property<string>("FiscalMonth");

                    b.Property<string>("FiscalYear");

                    b.Property<string>("Impressions");

                    b.Property<string>("TotalOnlineOrders");

                    b.Property<string>("TotalOnlineRevenue");

                    b.Property<string>("Visit");

                    b.HasKey("DisplayId");

                    b.ToTable("Displays");
                });

            modelBuilder.Entity("BizHacks.Models.Search", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BounceRate");

                    b.Property<string>("CTR");

                    b.Property<string>("CampaignName");

                    b.Property<string>("Clicks");

                    b.Property<string>("Cost");

                    b.Property<string>("FiscalMonth");

                    b.Property<string>("FiscalYear");

                    b.Property<string>("Impressions");

                    b.Property<string>("TotalOnlineOrders");

                    b.Property<string>("TotalOnlineRevenue");

                    b.Property<string>("Visit");

                    b.HasKey("SearchId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("BizHacks.Models.Social", b =>
                {
                    b.Property<int>("SocialId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BounceRate");

                    b.Property<string>("CTR");

                    b.Property<string>("CampaignName");

                    b.Property<string>("Clicks");

                    b.Property<string>("Cost");

                    b.Property<string>("FiscalMonth");

                    b.Property<string>("FiscalYear");

                    b.Property<string>("Impressions");

                    b.Property<string>("TotalOnlineOrders");

                    b.Property<string>("TotalOnlineRevenue");

                    b.Property<string>("Visit");

                    b.HasKey("SocialId");

                    b.ToTable("Socials");
                });
#pragma warning restore 612, 618
        }
    }
}
